### ISSUE TITLE
[FE]: RVI Terminal

### ISSUE THREAD

**Issue by AdamPiotrowski91** [AdamPiotrowski91/RVI_Ideas#55]
**Description:**
*(details of what and how should work)*
Basically, idea to have a terminal-like access point for RVI for advanced users.
Commands to access AC, ACM, GETrequest, etc. built-ins via commands.
Some way to perform more advanced actions within RVI or within Rally using RVI

**Additional Context & Ad Hoc Info:**
*(Add any other context about the problem here.)*

**Comment by AdamPiotrowski91** [comment]
# Brainstorming Comment

## Loose thoughts
 
Of course this will be a very simplified Terminal, but still, will allow access to something advanced, if needed.

Maybe a way to create macros?

## Actual ideas

- [ ] `cd <RallyItemID>` goes into Rally Item Details page, with Terminal ready to get or set some values for it
- [ ] `help` and/or `???` commands to display Usage for this terminal

**Comment by urszulajaczewska** [comment]
`cd ~` - get back to default page e.x. Iteration Status

**Comment by urszulajaczewska** [comment]
`rm`/`rm -f` - delete work item or `rm -rf` - delete work item with its children e.x. TS with TCs

**Comment by urszulajaczewska** [comment]
something like `mkdir` with option to choose work item type (with flag) to open new item creating page
